project_id = "qvzoeguwilqurujbnvem"

[functions.verify-turnstile]
verify_jwt = false

[functions.tempmail]
verify_jwt = false

[functions.bot-handler]
verify_jwt = false

[functions.public-query]
verify_jwt = false

[functions.create-share-link]
verify_jwt = false

[functions.register-bots]
verify_jwt = false

[functions.query-api]
verify_jwt = false
